--CREATEING DATABASE AND SCHEMAS--
USE MASTER;
GO
  IF EXISTS(SELECT 1 FROM sys.databases WHERE name="DataWarehouse")
  BEGIN
  ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Datawarehouse;
END;
GO
CREATE TABLE datawarehouse;
GO
USE Datawarehouse
GO 
CREATE SCHEMA bronze;
GO 
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO

